events
{
	worker_connections 1024;
}

http
{
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	server {
		listen 443 ssl;
		listen [::]:443 ssl;
		server_name fragarc2.42.fr;

		index index.php index.html index.htm;

		root /var/www/html;

		ssl_protocols TLSv1.3;
	    ssl_certificate /etc/nginx/ssl/inception.crt;
	    ssl_certificate_key /etc/nginx/ssl/inception.key;

		location / {

			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$ {
			include snippets/fastcgi-php.conf;
			fastcgi_pass wordpress:9000;
		}

		# deny access to .htaccess files, if Apache's document root
		# concurs with nginx's one
		#
		#location ~ /\.ht {
		#	deny all;
		#}
	}
}


# Virtual Host configuration for example.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
#
#server {
#	listen 80;
#	listen [::]:80;
#
#	server_name example.com;
#
#	root /var/www/example.com;
#	index index2.html;
#
#	location / {
#		try_files $uri $uri/ =404;
#	}
#}
